import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import NavBar from "../components/NavBar";

export default function Home() {
  return (
    <div>
      <Head>
        <title>INTERFACE FRONTEND</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="logo" href="/logo.png" />
      </Head>
      <header>
        <NavBar />
      </header>
      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" INTERFACE "}
          <span className={styles.logo}>
            <Image
              src="/logo.png"
              alt="Interface Logo"
              width={72}
              height={16}
            />
          </span>
        </a>
      </footer>
    </div>
  );
}
